### ISSUE TITLE
Skillenchatdata error when loading or save

### ISSUE THREAD

**Issue by pavelheiden** [ClaessicsGit/L2Homage#4]
Hello Bumble! It's me again, but this time I decided to try creating a bug report on github :)

After I downloaded and compiled the latest version of homage, I got this bug.

![error](https://user-images.githubusercontent.com/108584289/177473675-0918651a-a17f-47e8-a2a3-cacab7103aab.jpg)

This error shows up when I use my server and client files. If I use yours, then everything loads normally.

UPDATE: Even with your files, after the first attempt to save the files, I get the same errors. As I understand it, the _skill_pch_ files in the Data\Server folder break and become empty.

![Снимок](https://user-images.githubusercontent.com/108584289/177532430-bd21a62d-fc78-4285-8b47-0eda8f86d136.PNG)

Thanks for your work, have a nice day :)

**Comment by ClaessicsGit** [comment]
That looks like an input error, I'm not able to reproduce it
